//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snake_v1._2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snake_v1._2.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 按空格键继续游戏 的本地化字符串。
        /// </summary>
        internal static string blank_to_start_app {
            get {
                return ResourceManager.GetString("blank_to_start_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按回车键重新开始 的本地化字符串。
        /// </summary>
        internal static string enter_restart_app {
            get {
                return ResourceManager.GetString("enter_restart_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按ESC键退出游戏 的本地化字符串。
        /// </summary>
        internal static string esc_exit_app {
            get {
                return ResourceManager.GetString("esc_exit_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string exit_app {
            get {
                return ResourceManager.GetString("exit_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认退出游戏 的本地化字符串。
        /// </summary>
        internal static string exit_game_go_app {
            get {
                return ResourceManager.GetString("exit_game_go_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏结束 的本地化字符串。
        /// </summary>
        internal static string game_over_app {
            get {
                return ResourceManager.GetString("game_over_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币：  的本地化字符串。
        /// </summary>
        internal static string gold_props {
            get {
                return ResourceManager.GetString("gold_props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 猎人捉到你了 的本地化字符串。
        /// </summary>
        internal static string hunter_catch_tip {
            get {
                return ResourceManager.GetString("hunter_catch_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级：  的本地化字符串。
        /// </summary>
        internal static string level_props {
            get {
                return ResourceManager.GetString("level_props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生命值：  的本地化字符串。
        /// </summary>
        internal static string life_props {
            get {
                return ResourceManager.GetString("life_props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string pause_app {
            get {
                return ResourceManager.GetString("pause_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将会重置游戏，且当前记录不会保存，确认继续？ 的本地化字符串。
        /// </summary>
        internal static string restart_unsafe_go {
            get {
                return ResourceManager.GetString("restart_unsafe_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时：  的本地化字符串。
        /// </summary>
        internal static string time_props {
            get {
                return ResourceManager.GetString("time_props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏提示 的本地化字符串。
        /// </summary>
        internal static string tip_app {
            get {
                return ResourceManager.GetString("tip_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贪吃蛇 的本地化字符串。
        /// </summary>
        internal static string title_app {
            get {
                return ResourceManager.GetString("title_app", resourceCulture);
            }
        }
    }
}
